# scispaCy Multi-Model + Regex NER

This notebook runs multiple scispaCy biomedical NER models on the same input text and adds a regex layer for PHI, IDs, addresses, dates, medication instructions, labs, vitals, and clinical codes.

The output keeps the `source` column so you can see exactly which scispaCy model or regex pattern predicted each span.

## Install scispaCy Models

First install the root requirements:

```powershell
cd C:\Users\vasav\OneDrive\Documents\Deep-learning-Lab
python -m pip install -r requirements.txt
```

Then install the scispaCy model packages you want to use. The notebook will also print these commands if a model is missing.

```powershell
python -m pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_sm-0.5.4.tar.gz
python -m pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_bc5cdr_md-0.5.4.tar.gz
python -m pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_bionlp13cg_md-0.5.4.tar.gz
python -m pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_craft_md-0.5.4.tar.gz
python -m pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_jnlpba_md-0.5.4.tar.gz
```

The core scispaCy model `en_core_sci_sm` detects broad biomedical mentions. The NER models detect typed entities from their training corpora.

## Model Coverage

| Model | Main labels / purpose |
| --- | --- |
| `en_core_sci_sm` | General biomedical mention detector. Usually emits generic `ENTITY` spans. |
| `en_ner_bc5cdr_md` | `DISEASE`, `CHEMICAL` |
| `en_ner_bionlp13cg_md` | Anatomy/pathology/organ/tissue/cell/cancer/chemical style labels |
| `en_ner_craft_md` | `GGP`, `SO`, `TAXON`, `CHEBI`, `GO`, `CL` |
| `en_ner_jnlpba_md` | `DNA`, `CELL_TYPE`, `CELL_LINE`, `RNA`, `PROTEIN` |

Regex adds deterministic extraction for PHI and structured clinical patterns that scispaCy models do not reliably cover.

In [32]:
from __future__ import annotations

import re
from dataclasses import dataclass

import pandas as pd
import scispacy
import spacy

pd.set_option("display.max_colwidth", 160)

MODEL_INSTALL_URLS = {
    "en_core_sci_sm": "https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_sm-0.5.4.tar.gz",
    "en_ner_bc5cdr_md": "https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_bc5cdr_md-0.5.4.tar.gz",
    "en_ner_bionlp13cg_md": "https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_bionlp13cg_md-0.5.4.tar.gz",
    "en_ner_craft_md": "https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_craft_md-0.5.4.tar.gz",
    "en_ner_jnlpba_md": "https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_jnlpba_md-0.5.4.tar.gz",
}

SCISPACY_MODEL_SPECS = [
    {"name": "en_core_sci_sm", "purpose": "general biomedical mentions"},
    {"name": "en_ner_bc5cdr_md", "purpose": "disease and chemical"},
    {"name": "en_ner_bionlp13cg_md", "purpose": "anatomy, pathology, cancer, tissue, cell, chemicals"},
    {"name": "en_ner_craft_md", "purpose": "genes, chemicals, taxonomy, ontology/cell labels"},
    {"name": "en_ner_jnlpba_md", "purpose": "DNA, RNA, protein, cell type, cell line"},
]

## Input Text

Edit `input_text` and rerun the notebook to test another note.

In [33]:
input_text = """
On 03/12/2019 Dr. Smith at St. Mary's Hospital prescribed ibuprofen 400 mg PO twice daily for 7 days to Mr. John Jones, a 64-year-old male with severe knee pain and osteoarthritis.
MRN 123456, patient ID AB-9981, email john.jones@example.com, phone (555) 123-4567. He lives at 12 Main Street, Boston, MA 02118.
BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL.
ICD-10 E11.9 and CPT 99213 were recorded. The patient has a family history of cancer and prior knee arthroscopy.
""".strip()

input_text

"On 03/12/2019 Dr. Smith at St. Mary's Hospital prescribed ibuprofen 400 mg PO twice daily for 7 days to Mr. John Jones, a 64-year-old male with severe knee pain and osteoarthritis.\nMRN 123456, patient ID AB-9981, email john.jones@example.com, phone (555) 123-4567. He lives at 12 Main Street, Boston, MA 02118.\nBP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL.\nICD-10 E11.9 and CPT 99213 were recorded. The patient has a family history of cancer and prior knee arthroscopy."

## Load Available scispaCy Models

In [34]:
def load_available_scispacy_models(model_specs: list[dict]) -> dict[str, spacy.language.Language]:
    loaded = {}
    missing = []

    for spec in model_specs:
        name = spec["name"]
        try:
            loaded[name] = spacy.load(name)
            print(f"Loaded {name}: {spec['purpose']}")
        except OSError:
            missing.append(name)
            print(f"Missing {name}: {spec['purpose']}")

    if missing:
        print("\nInstall missing models with:")
        for name in missing:
            print(f"python -m pip install {MODEL_INSTALL_URLS[name]}")

    return loaded


loaded_models = load_available_scispacy_models(SCISPACY_MODEL_SPECS)
list(loaded_models)

C:\Users\vasav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\spacy\language.py:2195: FutureWarning: Possible set union at position 6328
  deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(  # type: ignore[union-attr]

Loaded en_core_sci_sm: general biomedical mentions
Loaded en_ner_bc5cdr_md: disease and chemical
Loaded en_ner_bionlp13cg_md: anatomy, pathology, cancer, tissue, cell, chemicals
Loaded en_ner_craft_md: genes, chemicals, taxonomy, ontology/cell labels
Loaded en_ner_jnlpba_md: DNA, RNA, protein, cell type, cell line

['en_core_sci_sm',
 'en_ner_bc5cdr_md',
 'en_ner_bionlp13cg_md',
 'en_ner_craft_md',
 'en_ner_jnlpba_md']

## Helper Functions

In [35]:
RESULT_COLUMNS = ["source", "method", "entity", "text", "start", "end", "score", "context"]


def context_window(text: str, start: int, end: int, window: int = 45) -> str:
    left = max(0, start - window)
    right = min(len(text), end + window)
    return text[left:right].replace("\n", " ")


def make_results_frame(rows: list[dict]) -> pd.DataFrame:
    if not rows:
        return pd.DataFrame(columns=RESULT_COLUMNS)

    df = pd.DataFrame(rows, columns=RESULT_COLUMNS)
    df = df.drop_duplicates(subset=["source", "method", "entity", "text", "start", "end"])
    return df.sort_values(["start", "end", "method", "source", "entity"]).reset_index(drop=True)

## Run scispaCy Models

In [36]:
def run_scispacy_models(text: str, models: dict[str, spacy.language.Language]) -> pd.DataFrame:
    rows = []

    for model_name, nlp in models.items():
        doc = nlp(text)
        for ent in doc.ents:
            rows.append(
                {
                    "source": model_name,
                    "method": "scispacy",
                    "entity": ent.label_,
                    "text": ent.text,
                    "start": ent.start_char,
                    "end": ent.end_char,
                    "score": None,
                    "context": context_window(text, ent.start_char, ent.end_char),
                }
            )

    return make_results_frame(rows)


scispacy_entities = run_scispacy_models(input_text, loaded_models)
scispacy_entities

,source,method,entity,text,start,end,score,context
0,en_core_sci_sm,scispacy,ENTITY,Dr. Smith,14,23,None,On 03/12/2019 Dr. Smith at St. Mary's Hospital prescribed ibuprofen
1,en_core_sci_sm,scispacy,ENTITY,St. Mary's Hospital,27,46,None,On 03/12/2019 Dr. Smith at St. Mary's Hospital prescribed ibuprofen 400 mg PO twice daily f
2,en_core_sci_sm,scispacy,ENTITY,ibuprofen,58,67,None,Dr. Smith at St. Mary's Hospital prescribed ibuprofen 400 mg PO twice daily for 7 days to Mr. John
3,en_ner_bc5cdr_md,scispacy,CHEMICAL,ibuprofen,58,67,None,Dr. Smith at St. Mary's Hospital prescribed ibuprofen 400 mg PO twice daily for 7 days to Mr. John
4,en_ner_bionlp13cg_md,scispacy,SIMPLE_CHEMICAL,ibuprofen,58,67,None,Dr. Smith at St. Mary's Hospital prescribed ibuprofen 400 mg PO twice daily for 7 days to Mr. John
5,en_core_sci_sm,scispacy,ENTITY,PO,75,77,None,"Mary's Hospital prescribed ibuprofen 400 mg PO twice daily for 7 days to Mr. John Jones, a"
6,en_core_sci_sm,scispacy,ENTITY,days,96,100,None,"cribed ibuprofen 400 mg PO twice daily for 7 days to Mr. John Jones, a 64-year-old male with s"
7,en_core_sci_sm,scispacy,ENTITY,Mr. John Jones,104,118,None,"buprofen 400 mg PO twice daily for 7 days to Mr. John Jones, a 64-year-old male with severe knee pain an"
8,en_ner_bionlp13cg_md,scispacy,ORGANISM,John Jones,108,118,None,"ofen 400 mg PO twice daily for 7 days to Mr. John Jones, a 64-year-old male with severe knee pain an"
9,en_core_sci_sm,scispacy,ENTITY,male,134,138,None,"for 7 days to Mr. John Jones, a 64-year-old male with severe knee pain and osteoarthritis. MR"
10,en_core_sci_sm,scispacy,ENTITY,severe,144,150,None,"s to Mr. John Jones, a 64-year-old male with severe knee pain and osteoarthritis. MRN 123456, pa"
11,en_core_sci_sm,scispacy,ENTITY,knee pain,151,160,None,". John Jones, a 64-year-old male with severe knee pain and osteoarthritis. MRN 123456, patient ID A"
12,en_ner_bc5cdr_md,scispacy,DISEASE,knee pain,151,160,None,". John Jones, a 64-year-old male with severe knee pain and osteoarthritis. MRN 123456, patient ID A"
13,en_core_sci_sm,scispacy,ENTITY,osteoarthritis,165,179,None,"a 64-year-old male with severe knee pain and osteoarthritis. MRN 123456, patient ID AB-9981, email john."
14,en_ner_bc5cdr_md,scispacy,DISEASE,osteoarthritis,165,179,None,"a 64-year-old male with severe knee pain and osteoarthritis. MRN 123456, patient ID AB-9981, email john."
15,en_ner_bionlp13cg_md,scispacy,CANCER,MRN,181,184,None,"le with severe knee pain and osteoarthritis. MRN 123456, patient ID AB-9981, email john.jones"
16,en_ner_jnlpba_md,scispacy,PROTEIN,MRN,181,184,None,"le with severe knee pain and osteoarthritis. MRN 123456, patient ID AB-9981, email john.jones"
17,en_core_sci_sm,scispacy,ENTITY,patient,193,200,None,"re knee pain and osteoarthritis. MRN 123456, patient ID AB-9981, email john.jones@example.com, ph"
18,en_ner_bionlp13cg_md,scispacy,ORGANISM,patient,193,200,None,"re knee pain and osteoarthritis. MRN 123456, patient ID AB-9981, email john.jones@example.com, ph"
19,en_core_sci_sm,scispacy,ENTITY,ID,201,203,None,"pain and osteoarthritis. MRN 123456, patient ID AB-9981, email john.jones@example.com, phone"
20,en_core_sci_sm,scispacy,ENTITY,AB-9981,204,211,None,"n and osteoarthritis. MRN 123456, patient ID AB-9981, email john.jones@example.com, phone (555) 1"
21,en_core_sci_sm,scispacy,ENTITY,email john.jones@example.com,213,241,None,"eoarthritis. MRN 123456, patient ID AB-9981, email john.jones@example.com, phone (555) 123-4567. He lives at 12 Main S"
22,en_ner_bionlp13cg_md,scispacy,CELL,john.jones@example.com,219,241,None,"ritis. MRN 123456, patient ID AB-9981, email john.jones@example.com, phone (555) 123-4567. He lives at 12 Main S"
23,en_core_sci_sm,scispacy,ENTITY,phone,243,248,None,"nt ID AB-9981, email john.jones@example.com, phone (555) 123-4567. He lives at 12 Main Street,"
24,en_core_sci_sm,scispacy,ENTITY,lives,268,273,None,".jones@example.com, phone (555) 123-4567. He lives at 12 Main Street, Boston, MA 02118. BP 140/"
25,en_core_sci_sm,scispacy,ENTITY,Boston,293,299,None,"(555) 123-4567. He lives at 12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, tempe"
26,en_core_sci_sm,scispacy,ENTITY,MA,301,303,None,"23-4567. He lives at 12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperatu"
27,en_ner_bionlp13cg_md,scispacy,GENE_OR_GENE_PRODUCT,MA,301,303,None,"23-4567. He lives at 12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperatu"
28,en_ner_jnlpba_md,scispacy,PROTEIN,MA,301,303,None,"23-4567. He lives at 12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperatu"
29,en_ner_bionlp13cg_md,scispacy,SIMPLE_CHEMICAL,BP,311,313,None,"e lives at 12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F,"
30,en_core_sci_sm,scispacy,ENTITY,HR,322,324,None,"12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine"
31,en_ner_bionlp13cg_md,scispacy,CANCER,HR,322,324,None,"12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine"
32,en_core_sci_sm,scispacy,ENTITY,SpO2,329,333,None,"Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/d"
33,en_ner_bionlp13cg_md,scispacy,GENE_OR_GENE_PRODUCT,SpO2,329,333,None,"Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/d"
34,en_ner_jnlpba_md,scispacy,PROTEIN,SpO2,329,333,None,"Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/d"
35,en_core_sci_sm,scispacy,ENTITY,temperature,339,350,None,"oston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WB"
36,en_core_sci_sm,scispacy,ENTITY,F,356,357,None,"BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2"
37,en_core_sci_sm,scispacy,ENTITY,creatinine,359,369,None,"140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10"
38,en_ner_bc5cdr_md,scispacy,CHEMICAL,creatinine,359,369,None,"140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10"
39,en_ner_bionlp13cg_md,scispacy,SIMPLE_CHEMICAL,creatinine,359,369,None,"140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10"
40,en_ner_craft_md,scispacy,CHEBI,creatinine,359,369,None,"140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10"
41,en_core_sci_sm,scispacy,ENTITY,HbA1c,381,386,None,"%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99"
42,en_core_sci_sm,scispacy,ENTITY,WBC,393,396,None,"re 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99213 were r"
43,en_ner_bionlp13cg_md,scispacy,CELL,WBC,393,396,None,"re 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99213 were r"
44,en_core_sci_sm,scispacy,ENTITY,K/uL.\nICD-10 E11.9,402,420,None,", creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99213 were recorded. The patient has"
45,en_ner_bc5cdr_md,scispacy,CHEMICAL,CPT,425,428,None,"HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99213 were recorded. The patient has a famil"
46,en_ner_bionlp13cg_md,scispacy,SIMPLE_CHEMICAL,CPT,425,428,None,"HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99213 were recorded. The patient has a famil"
47,en_ner_craft_md,scispacy,GGP,CPT,425,428,None,"HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99213 were recorded. The patient has a famil"
48,en_core_sci_sm,scispacy,ENTITY,CPT 99213,425,434,None,"HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99213 were recorded. The patient has a family hist"
49,en_core_sci_sm,scispacy,ENTITY,patient,454,461,None,CD-10 E11.9 and CPT 99213 were recorded. The patient has a family history of cancer and prior kne
50,en_ner_bionlp13cg_md,scispacy,ORGANISM,patient,454,461,None,CD-10 E11.9 and CPT 99213 were recorded. The patient has a family history of cancer and prior kne
51,en_core_sci_sm,scispacy,ENTITY,family history of cancer,468,492,None,d CPT 99213 were recorded. The patient has a family history of cancer and prior knee arthroscopy.
52,en_ner_bc5cdr_md,scispacy,DISEASE,cancer,486,492,None,ecorded. The patient has a family history of cancer and prior knee arthroscopy.
53,en_ner_bionlp13cg_md,scispacy,CANCER,cancer,486,492,None,ecorded. The patient has a family history of cancer and prior knee arthroscopy.
54,en_core_sci_sm,scispacy,ENTITY,prior,497,502,None,e patient has a family history of cancer and prior knee arthroscopy.
55,en_ner_bionlp13cg_md,scispacy,TISSUE,knee,503,507,None,ent has a family history of cancer and prior knee arthroscopy.
56,en_core_sci_sm,scispacy,ENTITY,knee arthroscopy,503,519,None,ent has a family history of cancer and prior knee arthroscopy.

## Regex Pattern Layer

These patterns catch structured clinical/PHI spans that model-based biomedical NER often misses. They are deterministic, so review false positives before using them in a production pipeline.

In [37]:
@dataclass(frozen=True)
class RegexPattern:
    entity: str
    pattern: str
    flags: int = re.IGNORECASE
    group: int = 0


REGEX_PATTERNS = [
    RegexPattern("EMAIL", r"\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b"),
    RegexPattern("PHONE", r"(?<!\d)(?:\+?1[-.\s]?)?(?:\(\d{3}\)|\d{3})[-.\s]?\d{3}[-.\s]?\d{4}(?!\d)"),
    RegexPattern("SSN", r"\b\d{3}-\d{2}-\d{4}\b"),
    RegexPattern("URL", r"\bhttps?://[^\s)]+"),
    RegexPattern("IP_ADDRESS", r"\b(?:\d{1,3}\.){3}\d{1,3}\b"),
    RegexPattern("DATE", r"\b(?:0?[1-9]|1[0-2])[/-](?:0?[1-9]|[12]\d|3[01])[/-](?:19|20)\d{2}\b"),
    RegexPattern("DATE", r"\b(?:19|20)\d{2}[-/](?:0?[1-9]|1[0-2])[-/](?:0?[1-9]|[12]\d|3[01])\b"),
    RegexPattern("DATE", r"\b(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)[a-z]*\.?\s+\d{1,2},?\s+(?:19|20)\d{2}\b"),
    RegexPattern("DATE_OF_BIRTH", r"\b(?:DOB|date of birth)\s*[:#-]?\s*(?:\d{1,2}[/-]\d{1,2}[/-](?:19|20)\d{2}|(?:19|20)\d{2}[-/]\d{1,2}[-/]\d{1,2})\b"),
    RegexPattern("TIME", r"\b\d{1,2}:\d{2}\s*(?:AM|PM|am|pm)?\b"),
    RegexPattern("AGE", r"\b(?:age(?:d)?\s*)?\d{1,3}\s*(?:-?\s*years? old|-?year-old|yo|y/o)\b|\bage\s*[:=]?\s*\d{1,3}\b"),
    RegexPattern("DOCTOR_NAME", r"\b(?:Dr|Doctor|Prof|Professor)\.?\s+[A-Z][a-z]+(?:\s+[A-Z][a-z]+){0,2}\b", 0),
    RegexPattern("PATIENT_NAME", r"\b(?:Mr|Mrs|Ms|Miss)\.?\s+[A-Z][a-z]+(?:\s+[A-Z][a-z]+){0,2}\b", 0),
    RegexPattern("PATIENT_NAME", r"\b(?:patient|pt|name)\s*(?:is|name|:)\s*([A-Z][a-z]+(?:\s+[A-Z][a-z]+){0,2})\b", re.IGNORECASE, 1),
    RegexPattern("HOSPITAL", r"\b((?:St\.?\s+)?[A-Z][A-Za-z'.-]+(?:\s+[A-Z][A-Za-z'.-]+){0,4}\s+(?:Hospital|Clinic|Medical Center|Health System|Healthcare|University Hospital|Cancer Center))\b", 0, 1),
    RegexPattern("ADDRESS", r"(?<![/.-])\b\d{1,6}\s+(?!(?:Dr|Doctor|Mr|Mrs|Ms|Prof)\.?\b)[A-Z0-9][A-Za-z0-9'.-]*(?:\s+[A-Za-z0-9'.-]+){0,5}\s+(?:Street|St|Avenue|Ave|Road|Rd|Boulevard|Blvd|Drive|Dr|Lane|Ln|Court|Ct|Way|Place|Pl)\.?\b(?:,\s*[A-Z][A-Za-z .'-]+)?(?:,\s*[A-Z]{2})?(?:\s+\d{5}(?:-\d{4})?)?"),
    RegexPattern("ZIP_CODE", r"(?<!CPT\s)\b\d{5}(?:-\d{4})?\b"),
    RegexPattern("CITY_STATE_ZIP", r"\b[A-Z][A-Za-z .'-]+,\s*[A-Z]{2}\s+\d{5}(?:-\d{4})?\b"),
    RegexPattern("MRN", r"\b(?:MRN|M\.?R\.?N\.?|medical record(?: number)?|record number)\s*[:#-]?\s*[A-Z0-9-]{4,}\b"),
    RegexPattern("PATIENT_ID", r"\b(?:patient|member|account|visit|encounter)\s*(?:id|number|no\.?)\s*[:#-]?\s*[A-Z0-9-]{3,}\b"),
    RegexPattern("NPI", r"\bNPI\s*[:#-]?\s*\d{10}\b"),
    RegexPattern("ICD10_CODE", r"\b[A-TV-Z][0-9][0-9AB](?:\.[0-9A-TV-Z]{1,4})?\b"),
    RegexPattern("CPT_CODE", r"\bCPT\s*[:#-]?\s*\d{5}\b"),
    RegexPattern("DOSAGE", r"\b\d+(?:\.\d+)?\s*(?:mg|mcg|g|kg|mL|ml|L|units?|IU|%)\b"),
    RegexPattern("FREQUENCY", r"\b(?:once|twice|three times|four times)\s+(?:daily|a day|per day|weekly|monthly)\b|\b(?:q\d{1,2}h|qhs|qid|tid|bid|prn|daily|weekly|monthly)\b"),
    RegexPattern("DURATION", r"\bfor\s+\d+\s+(?:hours?|days?|weeks?|months?|years?)\b"),
    RegexPattern("ROUTE", r"\b(?:PO|IV|IM|SC|SQ|subcutaneous|intravenous|intramuscular|oral|topical|inhaled|nasal|rectal)\b"),
    RegexPattern("MEDICATION_CONTEXT", r"\b(?:prescribed|started|taking|takes|given|administered)\s+([A-Za-z][A-Za-z-]{2,})\b", re.IGNORECASE, 1),
    RegexPattern("BLOOD_PRESSURE", r"\b(?:BP|blood pressure)\s*[:=]?\s*\d{2,3}/\d{2,3}\b"),
    RegexPattern("HEART_RATE", r"\b(?:HR|heart rate|pulse)\s*[:=]?\s*\d{2,3}\s*(?:bpm)?\b"),
    RegexPattern("TEMPERATURE", r"\b(?:temp(?:erature)?\s*[:=]?\s*)?\d{2,3}(?:\.\d)?\s*(?:F|C|deg F|deg C)\b"),
    RegexPattern("OXYGEN_SATURATION", r"\b(?:SpO2|O2 sat|oxygen saturation)\s*[:=]?\s*\d{2,3}%(?=\W|$)"),
    RegexPattern("LAB_VALUE", r"\b(?:WBC|RBC|Hgb|Hb|hemoglobin|platelets?|creatinine|glucose|sodium|potassium|HbA1c|A1c|ALT|AST|BUN|INR|CRP)\s*[:=]?\s*\d+(?:\.\d+)?(?:\s*(?:mg/dL|g/dL|mmol/L|mEq/L|K/uL|%|U/L|ng/mL))?\b"),
    RegexPattern("FAMILY_HISTORY", r"\bfamily history of\s+([A-Za-z][A-Za-z\s-]{2,40}?)(?=\.|,|;|\sand\s(?:prior|past|previous)|$)", re.IGNORECASE, 1),
]

In [38]:
def trim_span(text: str, start: int, end: int) -> tuple[str, int, int]:
    raw_span = text[start:end]
    stripped_span = raw_span.strip(" ,.;:\n\t")
    leading_trim = len(raw_span) - len(raw_span.lstrip(" ,.;:\n\t"))
    new_start = start + leading_trim
    new_end = new_start + len(stripped_span)
    return stripped_span, new_start, new_end


def run_regex_patterns(text: str, patterns: list[RegexPattern]) -> pd.DataFrame:
    rows = []

    for pattern_spec in patterns:
        compiled_pattern = re.compile(pattern_spec.pattern, pattern_spec.flags)
        for match in compiled_pattern.finditer(text):
            start, end = match.span(pattern_spec.group)
            if start < 0 or end < 0:
                continue

            span_text, start, end = trim_span(text, start, end)
            if not span_text:
                continue

            rows.append(
                {
                    "source": f"regex:{pattern_spec.entity}",
                    "method": "regex",
                    "entity": pattern_spec.entity,
                    "text": span_text,
                    "start": start,
                    "end": end,
                    "score": None,
                    "context": context_window(text, start, end),
                }
            )

    return make_results_frame(rows)


regex_entities = run_regex_patterns(input_text, REGEX_PATTERNS)
regex_entities

,source,method,entity,text,start,end,score,context
0,regex:DATE,regex,DATE,03/12/2019,3,13,None,On 03/12/2019 Dr. Smith at St. Mary's Hospital prescribed
1,regex:DOCTOR_NAME,regex,DOCTOR_NAME,Dr. Smith,14,23,None,On 03/12/2019 Dr. Smith at St. Mary's Hospital prescribed ibuprofen
2,regex:HOSPITAL,regex,HOSPITAL,St. Mary's Hospital,27,46,None,On 03/12/2019 Dr. Smith at St. Mary's Hospital prescribed ibuprofen 400 mg PO twice daily f
3,regex:MEDICATION_CONTEXT,regex,MEDICATION_CONTEXT,ibuprofen,58,67,None,Dr. Smith at St. Mary's Hospital prescribed ibuprofen 400 mg PO twice daily for 7 days to Mr. John
4,regex:DOSAGE,regex,DOSAGE,400 mg,68,74,None,"at St. Mary's Hospital prescribed ibuprofen 400 mg PO twice daily for 7 days to Mr. John Jones,"
5,regex:ROUTE,regex,ROUTE,PO,75,77,None,"Mary's Hospital prescribed ibuprofen 400 mg PO twice daily for 7 days to Mr. John Jones, a"
6,regex:FREQUENCY,regex,FREQUENCY,twice daily,78,89,None,"ry's Hospital prescribed ibuprofen 400 mg PO twice daily for 7 days to Mr. John Jones, a 64-year-old"
7,regex:DURATION,regex,DURATION,for 7 days,90,100,None,"l prescribed ibuprofen 400 mg PO twice daily for 7 days to Mr. John Jones, a 64-year-old male with s"
8,regex:PATIENT_NAME,regex,PATIENT_NAME,Mr. John Jones,104,118,None,"buprofen 400 mg PO twice daily for 7 days to Mr. John Jones, a 64-year-old male with severe knee pain an"
9,regex:AGE,regex,AGE,64-year-old,122,133,None,"twice daily for 7 days to Mr. John Jones, a 64-year-old male with severe knee pain and osteoarthriti"
10,regex:MRN,regex,MRN,MRN 123456,181,191,None,"le with severe knee pain and osteoarthritis. MRN 123456, patient ID AB-9981, email john.jones@exampl"
11,regex:PATIENT_ID,regex,PATIENT_ID,patient ID AB-9981,193,211,None,"re knee pain and osteoarthritis. MRN 123456, patient ID AB-9981, email john.jones@example.com, phone (555) 1"
12,regex:EMAIL,regex,EMAIL,john.jones@example.com,219,241,None,"ritis. MRN 123456, patient ID AB-9981, email john.jones@example.com, phone (555) 123-4567. He lives at 12 Main S"
13,regex:PHONE,regex,PHONE,(555) 123-4567,249,263,None,"AB-9981, email john.jones@example.com, phone (555) 123-4567. He lives at 12 Main Street, Boston, MA 0211"
14,regex:ADDRESS,regex,ADDRESS,"12 Main Street, Boston, MA 02118",277,309,None,"ample.com, phone (555) 123-4567. He lives at 12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98."
15,regex:CITY_STATE_ZIP,regex,CITY_STATE_ZIP,"Boston, MA 02118",293,309,None,"(555) 123-4567. He lives at 12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98."
16,regex:ZIP_CODE,regex,ZIP_CODE,02118,304,309,None,"4567. He lives at 12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98."
17,regex:BLOOD_PRESSURE,regex,BLOOD_PRESSURE,BP 140/90,311,320,None,"e lives at 12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creati"
18,regex:HEART_RATE,regex,HEART_RATE,HR 88,322,327,None,"12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1."
19,regex:OXYGEN_SATURATION,regex,OXYGEN_SATURATION,SpO2 97%,329,337,None,"Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, H"
20,regex:TEMPERATURE,regex,TEMPERATURE,temperature 98.6 F,339,357,None,"oston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2"
21,regex:LAB_VALUE,regex,LAB_VALUE,creatinine 1.4 mg/dL,359,379,None,"140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and"
22,regex:DOSAGE,regex,DOSAGE,1.4 mg,370,376,None,"88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9"
23,regex:LAB_VALUE,regex,LAB_VALUE,HbA1c 7.2,381,390,None,"%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99213"
24,regex:LAB_VALUE,regex,LAB_VALUE,WBC 11.2 K/uL,393,406,None,"re 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99213 were recorded. T"
25,regex:ICD10_CODE,regex,ICD10_CODE,E11.9,415,420,None,"1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99213 were recorded. The patient has"
26,regex:CPT_CODE,regex,CPT_CODE,CPT 99213,425,434,None,"HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99213 were recorded. The patient has a family hist"
27,regex:FAMILY_HISTORY,regex,FAMILY_HISTORY,cancer,486,492,None,ecorded. The patient has a family history of cancer and prior knee arthroscopy.

## Combined Results By Source

This table shows every prediction from every loaded scispaCy model and every regex pattern.

In [39]:
all_entities = make_results_frame(
    pd.concat([scispacy_entities, regex_entities], ignore_index=True).to_dict("records")
)

all_entities

,source,method,entity,text,start,end,score,context
0,regex:DATE,regex,DATE,03/12/2019,3,13,None,On 03/12/2019 Dr. Smith at St. Mary's Hospital prescribed
1,regex:DOCTOR_NAME,regex,DOCTOR_NAME,Dr. Smith,14,23,None,On 03/12/2019 Dr. Smith at St. Mary's Hospital prescribed ibuprofen
2,en_core_sci_sm,scispacy,ENTITY,Dr. Smith,14,23,None,On 03/12/2019 Dr. Smith at St. Mary's Hospital prescribed ibuprofen
3,regex:HOSPITAL,regex,HOSPITAL,St. Mary's Hospital,27,46,None,On 03/12/2019 Dr. Smith at St. Mary's Hospital prescribed ibuprofen 400 mg PO twice daily f
4,en_core_sci_sm,scispacy,ENTITY,St. Mary's Hospital,27,46,None,On 03/12/2019 Dr. Smith at St. Mary's Hospital prescribed ibuprofen 400 mg PO twice daily f
...,...,...,...,...,...,...,...,...
80,en_ner_bc5cdr_md,scispacy,DISEASE,cancer,486,492,None,ecorded. The patient has a family history of cancer and prior knee arthroscopy.
81,en_ner_bionlp13cg_md,scispacy,CANCER,cancer,486,492,None,ecorded. The patient has a family history of cancer and prior knee arthroscopy.
82,en_core_sci_sm,scispacy,ENTITY,prior,497,502,None,e patient has a family history of cancer and prior knee arthroscopy.
83,en_ner_bionlp13cg_md,scispacy,TISSUE,knee,503,507,None,ent has a family history of cancer and prior knee arthroscopy.
84,en_core_sci_sm,scispacy,ENTITY,knee arthroscopy,503,519,None,ent has a family history of cancer and prior knee arthroscopy.

## Combined Span Summary

This groups overlapping exact spans so you can see which models or regex patterns agreed on the same text.

In [40]:
if all_entities.empty:
    span_summary = pd.DataFrame(columns=["text", "start", "end", "entities", "sources", "methods", "context"])
else:
    span_summary = (
        all_entities.groupby(["start", "end", "text"], as_index=False)
        .agg(
            entities=("entity", lambda values: ", ".join(sorted(set(values)))),
            sources=("source", lambda values: ", ".join(sorted(set(values)))),
            methods=("method", lambda values: ", ".join(sorted(set(values)))),
            context=("context", "first"),
        )
        .sort_values(["start", "end"])
        .reset_index(drop=True)
    )

span_summary

,start,end,text,entities,sources,methods,context
0,3,13,03/12/2019,DATE,regex:DATE,regex,On 03/12/2019 Dr. Smith at St. Mary's Hospital prescribed
1,14,23,Dr. Smith,"DOCTOR_NAME, ENTITY","en_core_sci_sm, regex:DOCTOR_NAME","regex, scispacy",On 03/12/2019 Dr. Smith at St. Mary's Hospital prescribed ibuprofen
2,27,46,St. Mary's Hospital,"ENTITY, HOSPITAL","en_core_sci_sm, regex:HOSPITAL","regex, scispacy",On 03/12/2019 Dr. Smith at St. Mary's Hospital prescribed ibuprofen 400 mg PO twice daily f
3,58,67,ibuprofen,"CHEMICAL, ENTITY, MEDICATION_CONTEXT, SIMPLE_CHEMICAL","en_core_sci_sm, en_ner_bc5cdr_md, en_ner_bionlp13cg_md, regex:MEDICATION_CONTEXT","regex, scispacy",Dr. Smith at St. Mary's Hospital prescribed ibuprofen 400 mg PO twice daily for 7 days to Mr. John
4,68,74,400 mg,DOSAGE,regex:DOSAGE,regex,"at St. Mary's Hospital prescribed ibuprofen 400 mg PO twice daily for 7 days to Mr. John Jones,"
5,75,77,PO,"ENTITY, ROUTE","en_core_sci_sm, regex:ROUTE","regex, scispacy","Mary's Hospital prescribed ibuprofen 400 mg PO twice daily for 7 days to Mr. John Jones, a"
6,78,89,twice daily,FREQUENCY,regex:FREQUENCY,regex,"ry's Hospital prescribed ibuprofen 400 mg PO twice daily for 7 days to Mr. John Jones, a 64-year-old"
7,90,100,for 7 days,DURATION,regex:DURATION,regex,"l prescribed ibuprofen 400 mg PO twice daily for 7 days to Mr. John Jones, a 64-year-old male with s"
8,96,100,days,ENTITY,en_core_sci_sm,scispacy,"cribed ibuprofen 400 mg PO twice daily for 7 days to Mr. John Jones, a 64-year-old male with s"
9,104,118,Mr. John Jones,"ENTITY, PATIENT_NAME","en_core_sci_sm, regex:PATIENT_NAME","regex, scispacy","buprofen 400 mg PO twice daily for 7 days to Mr. John Jones, a 64-year-old male with severe knee pain an"
10,108,118,John Jones,ORGANISM,en_ner_bionlp13cg_md,scispacy,"ofen 400 mg PO twice daily for 7 days to Mr. John Jones, a 64-year-old male with severe knee pain an"
11,122,133,64-year-old,AGE,regex:AGE,regex,"twice daily for 7 days to Mr. John Jones, a 64-year-old male with severe knee pain and osteoarthriti"
12,134,138,male,ENTITY,en_core_sci_sm,scispacy,"for 7 days to Mr. John Jones, a 64-year-old male with severe knee pain and osteoarthritis. MR"
13,144,150,severe,ENTITY,en_core_sci_sm,scispacy,"s to Mr. John Jones, a 64-year-old male with severe knee pain and osteoarthritis. MRN 123456, pa"
14,151,160,knee pain,"DISEASE, ENTITY","en_core_sci_sm, en_ner_bc5cdr_md",scispacy,". John Jones, a 64-year-old male with severe knee pain and osteoarthritis. MRN 123456, patient ID A"
15,165,179,osteoarthritis,"DISEASE, ENTITY","en_core_sci_sm, en_ner_bc5cdr_md",scispacy,"a 64-year-old male with severe knee pain and osteoarthritis. MRN 123456, patient ID AB-9981, email john."
16,181,184,MRN,"CANCER, PROTEIN","en_ner_bionlp13cg_md, en_ner_jnlpba_md",scispacy,"le with severe knee pain and osteoarthritis. MRN 123456, patient ID AB-9981, email john.jones"
17,181,191,MRN 123456,MRN,regex:MRN,regex,"le with severe knee pain and osteoarthritis. MRN 123456, patient ID AB-9981, email john.jones@exampl"
18,193,200,patient,"ENTITY, ORGANISM","en_core_sci_sm, en_ner_bionlp13cg_md",scispacy,"re knee pain and osteoarthritis. MRN 123456, patient ID AB-9981, email john.jones@example.com, ph"
19,193,211,patient ID AB-9981,PATIENT_ID,regex:PATIENT_ID,regex,"re knee pain and osteoarthritis. MRN 123456, patient ID AB-9981, email john.jones@example.com, phone (555) 1"
20,201,203,ID,ENTITY,en_core_sci_sm,scispacy,"pain and osteoarthritis. MRN 123456, patient ID AB-9981, email john.jones@example.com, phone"
21,204,211,AB-9981,ENTITY,en_core_sci_sm,scispacy,"n and osteoarthritis. MRN 123456, patient ID AB-9981, email john.jones@example.com, phone (555) 1"
22,213,241,email john.jones@example.com,ENTITY,en_core_sci_sm,scispacy,"eoarthritis. MRN 123456, patient ID AB-9981, email john.jones@example.com, phone (555) 123-4567. He lives at 12 Main S"
23,219,241,john.jones@example.com,"CELL, EMAIL","en_ner_bionlp13cg_md, regex:EMAIL","regex, scispacy","ritis. MRN 123456, patient ID AB-9981, email john.jones@example.com, phone (555) 123-4567. He lives at 12 Main S"
24,243,248,phone,ENTITY,en_core_sci_sm,scispacy,"nt ID AB-9981, email john.jones@example.com, phone (555) 123-4567. He lives at 12 Main Street,"
25,249,263,(555) 123-4567,PHONE,regex:PHONE,regex,"AB-9981, email john.jones@example.com, phone (555) 123-4567. He lives at 12 Main Street, Boston, MA 0211"
26,268,273,lives,ENTITY,en_core_sci_sm,scispacy,".jones@example.com, phone (555) 123-4567. He lives at 12 Main Street, Boston, MA 02118. BP 140/"
27,277,309,"12 Main Street, Boston, MA 02118",ADDRESS,regex:ADDRESS,regex,"ample.com, phone (555) 123-4567. He lives at 12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98."
28,293,299,Boston,ENTITY,en_core_sci_sm,scispacy,"(555) 123-4567. He lives at 12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, tempe"
29,293,309,"Boston, MA 02118",CITY_STATE_ZIP,regex:CITY_STATE_ZIP,regex,"(555) 123-4567. He lives at 12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98."
30,301,303,MA,"ENTITY, GENE_OR_GENE_PRODUCT, PROTEIN","en_core_sci_sm, en_ner_bionlp13cg_md, en_ner_jnlpba_md",scispacy,"23-4567. He lives at 12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperatu"
31,304,309,02118,ZIP_CODE,regex:ZIP_CODE,regex,"4567. He lives at 12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98."
32,311,313,BP,SIMPLE_CHEMICAL,en_ner_bionlp13cg_md,scispacy,"e lives at 12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F,"
33,311,320,BP 140/90,BLOOD_PRESSURE,regex:BLOOD_PRESSURE,regex,"e lives at 12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creati"
34,322,324,HR,"CANCER, ENTITY","en_core_sci_sm, en_ner_bionlp13cg_md",scispacy,"12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine"
35,322,327,HR 88,HEART_RATE,regex:HEART_RATE,regex,"12 Main Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1."
36,329,333,SpO2,"ENTITY, GENE_OR_GENE_PRODUCT, PROTEIN","en_core_sci_sm, en_ner_bionlp13cg_md, en_ner_jnlpba_md",scispacy,"Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/d"
37,329,337,SpO2 97%,OXYGEN_SATURATION,regex:OXYGEN_SATURATION,regex,"Street, Boston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, H"
38,339,350,temperature,ENTITY,en_core_sci_sm,scispacy,"oston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WB"
39,339,357,temperature 98.6 F,TEMPERATURE,regex:TEMPERATURE,regex,"oston, MA 02118. BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2"
40,356,357,F,ENTITY,en_core_sci_sm,scispacy,"BP 140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2"
41,359,369,creatinine,"CHEBI, CHEMICAL, ENTITY, SIMPLE_CHEMICAL","en_core_sci_sm, en_ner_bc5cdr_md, en_ner_bionlp13cg_md, en_ner_craft_md",scispacy,"140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10"
42,359,379,creatinine 1.4 mg/dL,LAB_VALUE,regex:LAB_VALUE,regex,"140/90, HR 88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and"
43,370,376,1.4 mg,DOSAGE,regex:DOSAGE,regex,"88, SpO2 97%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9"
44,381,386,HbA1c,ENTITY,en_core_sci_sm,scispacy,"%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99"
45,381,390,HbA1c 7.2,LAB_VALUE,regex:LAB_VALUE,regex,"%, temperature 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99213"
46,393,396,WBC,"CELL, ENTITY","en_core_sci_sm, en_ner_bionlp13cg_md",scispacy,"re 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99213 were r"
47,393,406,WBC 11.2 K/uL,LAB_VALUE,regex:LAB_VALUE,regex,"re 98.6 F, creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99213 were recorded. T"
48,402,420,K/uL.\nICD-10 E11.9,ENTITY,en_core_sci_sm,scispacy,", creatinine 1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99213 were recorded. The patient has"
49,415,420,E11.9,ICD10_CODE,regex:ICD10_CODE,regex,"1.4 mg/dL, HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99213 were recorded. The patient has"
50,425,428,CPT,"CHEMICAL, GGP, SIMPLE_CHEMICAL","en_ner_bc5cdr_md, en_ner_bionlp13cg_md, en_ner_craft_md",scispacy,"HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99213 were recorded. The patient has a famil"
51,425,434,CPT 99213,"CPT_CODE, ENTITY","en_core_sci_sm, regex:CPT_CODE","regex, scispacy","HbA1c 7.2%, WBC 11.2 K/uL. ICD-10 E11.9 and CPT 99213 were recorded. The patient has a family hist"
52,454,461,patient,"ENTITY, ORGANISM","en_core_sci_sm, en_ner_bionlp13cg_md",scispacy,CD-10 E11.9 and CPT 99213 were recorded. The patient has a family history of cancer and prior kne
53,468,492,family history of cancer,ENTITY,en_core_sci_sm,scispacy,d CPT 99213 were recorded. The patient has a family history of cancer and prior knee arthroscopy.
54,486,492,cancer,"CANCER, DISEASE, FAMILY_HISTORY","en_ner_bc5cdr_md, en_ner_bionlp13cg_md, regex:FAMILY_HISTORY","regex, scispacy",ecorded. The patient has a family history of cancer and prior knee arthroscopy.
55,497,502,prior,ENTITY,en_core_sci_sm,scispacy,e patient has a family history of cancer and prior knee arthroscopy.
56,503,507,knee,TISSUE,en_ner_bionlp13cg_md,scispacy,ent has a family history of cancer and prior knee arthroscopy.
57,503,519,knee arthroscopy,ENTITY,en_core_sci_sm,scispacy,ent has a family history of cancer and prior knee arthroscopy.

## Quick Entity Type Counts

In [41]:
if all_entities.empty:
    entity_counts = pd.DataFrame(columns=["method", "source", "entity", "count"])
else:
    entity_counts = (
        all_entities.groupby(["method", "source", "entity"])
        .size()
        .reset_index(name="count")
        .sort_values(["method", "source", "entity"])
        .reset_index(drop=True)
    )

entity_counts

      method                    source                entity  count
0      regex             regex:ADDRESS               ADDRESS      1
1      regex                 regex:AGE                   AGE      1
2      regex      regex:BLOOD_PRESSURE        BLOOD_PRESSURE      1
3      regex      regex:CITY_STATE_ZIP        CITY_STATE_ZIP      1
4      regex            regex:CPT_CODE              CPT_CODE      1
5      regex                regex:DATE                  DATE      1
6      regex         regex:DOCTOR_NAME           DOCTOR_NAME      1
7      regex              regex:DOSAGE                DOSAGE      2
8      regex            regex:DURATION              DURATION      1
9      regex               regex:EMAIL                 EMAIL      1
10     regex      regex:FAMILY_HISTORY        FAMILY_HISTORY      1
11     regex           regex:FREQUENCY             FREQUENCY      1
12     regex          regex:HEART_RATE            HEART_RATE      1
13     regex            regex:HOSPITAL              HOSPITAL      1
14     regex          regex:ICD10_CODE            ICD10_CODE      1
15     regex           regex:LAB_VALUE             LAB_VALUE      3
16     regex  regex:MEDICATION_CONTEXT    MEDICATION_CONTEXT      1
17     regex                 regex:MRN                   MRN      1
18     regex   regex:OXYGEN_SATURATION     OXYGEN_SATURATION      1
19     regex          regex:PATIENT_ID            PATIENT_ID      1
20     regex        regex:PATIENT_NAME          PATIENT_NAME      1
21     regex               regex:PHONE                 PHONE      1
22     regex               regex:ROUTE                 ROUTE      1
23     regex         regex:TEMPERATURE           TEMPERATURE      1
24     regex            regex:ZIP_CODE              ZIP_CODE      1
25  scispacy            en_core_sci_sm                ENTITY     31
26  scispacy          en_ner_bc5cdr_md              CHEMICAL      3
27  scispacy          en_ner_bc5cdr_md               DISEASE      3
28  scispacy      en_ner_bionlp13cg_md                CANCER      3
29  scispacy      en_ner_bionlp13cg_md                  CELL      2
30  scispacy      en_ner_bionlp13cg_md  GENE_OR_GENE_PRODUCT      2
31  scispacy      en_ner_bionlp13cg_md              ORGANISM      3
32  scispacy      en_ner_bionlp13cg_md       SIMPLE_CHEMICAL      4
33  scispacy      en_ner_bionlp13cg_md                TISSUE      1
34  scispacy           en_ner_craft_md                 CHEBI      1
35  scispacy           en_ner_craft_md                   GGP      1
36  scispacy          en_ner_jnlpba_md               PROTEIN      3